server:
  port: 9527
default-lazy-init: false

############################################### data source(mysql) ############################################
spring:
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://172.22.82.100:3306/gcb_report?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3307/geek?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    hikari:
      auto-commit: false
      connection-timeout: 5000
      maximum-pool-size: 15
